VDPN-1/VDPN-25 BE - Create DB model
DISI2024/30643_CucosArtene_GeorgeEmanuel_TravelPoints_backend pull request #3
Opened 2024-04-06 19:27 UTC by Alina-Aurica

1. I removed the fields: visitHour, visitMonth, and numberOfVisits from VisitStatistics, as I believe these should be derived through a service that analyzes all the records in this table.
2. I included an isLogged field in the User model to enhance the notification feature.

2024-04-06 21:07 UTC, iDietzer requested changes

2024-04-06 21:07 UTC, iDietzer commented on TravelPoints-BackEnd/pom.xml
> +        </dependency>
C: make sure everything in indented correctly

2024-04-06 21:07 UTC, iDietzer commented on TravelPoints-BackEnd/src/main/java/com/example/travelpointsbackend/model/AttractionDetail.java
> +    private String offers;
M: use `@Column(<<column_name>>)` for every field (See here: https://www.geeksforgeeks.org/spring-data-jpa-column-annotation/?ref=lbp)

2024-04-06 21:07 UTC, iDietzer commented on TravelPoints-BackEnd/src/main/java/com/example/travelpointsbackend/model/Review.java
> +    private Timestamp createdAt;
M: see above, also use mappings for relations between tables. (See here: https://stackabuse.com/a-guide-to-jpa-with-hibernate-relationship-mapping/)

2024-04-06 21:07 UTC, iDietzer commented on TravelPoints-BackEnd/src/main/java/com/example/travelpointsbackend/model/TouristAttraction.java
> +    private Timestamp createdAt;
M: see above

2024-04-06 21:07 UTC, iDietzer commented on TravelPoints-BackEnd/src/main/java/com/example/travelpointsbackend/model/User.java
> +    private boolean isLogged;
M: see above

2024-04-06 21:07 UTC, iDietzer commented on TravelPoints-BackEnd/src/main/java/com/example/travelpointsbackend/model/UserWishlist.java
> +
M: see above

2024-04-07 12:00 UTC, Alina-Aurica commented on TravelPoints-BackEnd/pom.xml
> +        </dependency>
On my PC looks good
![image](https://github.com/DISI2024/30643_CucosArtene_GeorgeEmanuel_TravelPoints_backend/assets/84973358/88f5c480-c4de-4998-859a-42f400036642)

2024-04-08 06:03 UTC, iDietzer approved these changes

2024-04-08 08:20 UTC, merged